{% set name = "python-relion" %}
{% set pypi = "relion" %}
{% set version = "0.10.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi[0] }}/{{ pypi }}/relion-{{ version }}.tar.gz
  sha256: 9cf4336d5ac5714b21dd55990f8520b4dc34afa63f4e75f41269ac7a1bbeba5f

build:
  number: 0
  noarch: python
  entry_points:
    - relipy.job = relion.cli.current_job:run
    - relipy.show = relion.cli.pipeline_viewer:run
    - relipy.run_pipeline = relion.cli.run_pipeline:run
    - relipy.print_options = relion.cli.print_default_options:run
    - external_job_mask_soft_edge = relion.cryolo_relion_it.mask_soft_edge_external_job:main
    - external_job_select_and_split = relion.cryolo_relion_it.select_and_split_external_job:main
    - external_job_reconstruct_halves = relion.cryolo_relion_it.reconstruct_halves_external_job:main
    - external_job_fsc_fitting = relion.cryolo_relion_it.fsc_fitting_external_job:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - gemmi
    - ispyb
    - matplotlib-base
    - mrcfile
    - numpy
    - pandas
    - pillow
    - plotly
    - python >=3.8
    - pyyaml

test:
  imports:
    - relion
  commands:
    - pip check
    - relipy.job --help
    - relipy.show --help
    - relipy.run_pipeline --help
    - relipy.print_options --help
    - external_job_mask_soft_edge --help
    - external_job_select_and_split --help
    - external_job_reconstruct_halves --help
    - external_job_fsc_fitting --help
  requires:
    - pip

about:
  home: https://pypi.org/project/relion/
  summary: Relion Python API
  license: GPL-2.0-only
  license_file: LICENSE
  dev_url: https://github.com/DiamondLightSource/python-relion

extra:
  recipe-maintainers:
    - anthchirp
    - colinpalmer
    - d-j-hatton
    - horstmanna
